# Generated by Django 4.0.5 on 2022-06-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoBar', models.CharField(max_length=50)),
                ('ubicacion', models.TextField()),
                ('menu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PuebloMagico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('hospedaje', models.BooleanField()),
                ('zonas_culturales', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.DurationField()),
            ],
        ),
    ]
