# Generated by Django 4.0.5 on 2022-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoJWN', '0002_alter_bar_options_alter_cancion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('accommodation', models.BooleanField(verbose_name='Hospedaje')),
                ('culturalZones', models.BooleanField(verbose_name='Zonas culturales')),
            ],
            options={
                'verbose_name': 'pueblo magico',
                'verbose_name_plural': 'pueblos magicos',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('artist', models.CharField(max_length=50, verbose_name='Artista')),
                ('album', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50, verbose_name='Genero')),
                ('duration', models.DurationField(verbose_name='Duracion')),
            ],
            options={
                'verbose_name': 'cancion',
                'verbose_name_plural': 'canciones',
                'ordering': ['-title'],
            },
        ),
        migrations.DeleteModel(
            name='Cancion',
        ),
        migrations.DeleteModel(
            name='PuebloMagico',
        ),
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['-title'], 'verbose_name': 'bar', 'verbose_name_plural': 'barres'},
        ),
        migrations.RemoveField(
            model_name='bar',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='tipoBar',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='bar',
            name='barKind',
            field=models.CharField(default='Bebidas', max_length=50, verbose_name='Tipo de bar'),
        ),
        migrations.AddField(
            model_name='bar',
            name='location',
            field=models.TextField(default='escribe la dirrecion', verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='bar',
            name='title',
            field=models.CharField(default='morena', max_length=50, verbose_name='Título'),
        ),
    ]
