# Generated by Django 4.0.5 on 2022-06-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoJWN', '0003_magictown_song_delete_cancion_delete_pueblomagico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='barKind',
            field=models.CharField(max_length=50, verbose_name='Tipo de bar'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='location',
            field=models.TextField(verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
