# Generated by Django 4.0.5 on 2022-06-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoJWN', '0004_alter_bar_barkind_alter_bar_location_alter_bar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image',
            field=models.ImageField(default='asd', upload_to='', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='magictown',
            name='image',
            field=models.ImageField(default='asd', upload_to='', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='asd', upload_to='', verbose_name='Imagen'),
        ),
    ]
