# Generated by Django 4.0.5 on 2022-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoJWN', '0005_bar_image_magictown_image_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='magictown',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
    ]
