# Generated by Django 4.0.5 on 2022-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipoJWN', '0007_alter_bar_image_alter_magictown_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.ImageField(upload_to='bars', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='magictown',
            name='image',
            field=models.ImageField(upload_to='towns', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='songs', verbose_name='Imagen'),
        ),
    ]
