# Generated by Django 4.0.4 on 2022-06-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anime', models.CharField(max_length=100)),
                ('descripcion_anime', models.TextField()),
                ('genero_anime', models.TextField()),
                ('calificacion_anime', models.TextField()),
            ],
        ),
    ]
