# Generated by Django 4.0.4 on 2022-06-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='calificacion_anime',
            new_name='imagen_anime',
        ),
    ]
