# Generated by Django 4.0.4 on 2022-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.TextField()),
                ('author_book', models.TextField()),
                ('count_sale_book', models.TextField()),
                ('image_book', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_lastName', models.TextField()),
                ('user_addres', models.TextField()),
                ('user_celphone', models.TextField()),
                ('reference_bookUser', models.TextField()),
                ('user_status', models.BooleanField()),
            ],
        ),
    ]
