# Generated by Django 4.0.4 on 2022-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('ApellidoP', models.CharField(max_length=50)),
                ('ApellidoM', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Numero_de_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Debolucion_de_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.IntegerField()),
                ('Fecha', models.IntegerField()),
                ('Numero_de_Usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('ApellidoP', models.CharField(max_length=50)),
                ('ApellidoM', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Numero_de_empleado', models.IntegerField()),
                ('Seccion_de_trabajo', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Estantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_de_obras', models.CharField(max_length=25)),
                ('Alfabetisacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Autor', models.CharField(max_length=65)),
                ('fecha_de_publicasion', models.DateField()),
                ('ID_libro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Obtension_de_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.IntegerField()),
                ('Fecha', models.IntegerField()),
                ('Numero_de_Usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('ApellidoP', models.CharField(max_length=50)),
                ('ApellidoM', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Numero_de_usuario', models.IntegerField()),
            ],
        ),
    ]
