# Generated by Django 4.0.4 on 2022-06-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
