# Generated by Django 4.0.4 on 2022-06-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='content',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo del Videojuego'),
        ),
    ]
