# Generated by Django 4.0.4 on 2022-06-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0004_alter_videogame_content_alter_videogame_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion')),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='videogames.category', verbose_name='Categorias'),
        ),
    ]
