# Generated by Django 4.0.4 on 2022-06-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0005_category_videogame_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['-created'], 'verbose_name': 'videojuego', 'verbose_name_plural': 'videjuegos'},
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
