# Generated by Django 4.0.4 on 2022-06-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0006_alter_videogame_options_remove_videogame_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['-created'], 'verbose_name': 'videojuego', 'verbose_name_plural': 'videojuegos'},
        ),
    ]
