# Generated by Django 4.0.4 on 2022-06-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0007_alter_videogame_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo del Videojuego')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Plataforma')),
                ('calification', models.CharField(max_length=200, verbose_name='Calificación')),
                ('genero', models.CharField(max_length=200, verbose_name='Genero')),
                ('year', models.CharField(max_length=200, verbose_name='Año de lanzamiento')),
                ('content', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='videogames', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion')),
            ],
            options={
                'verbose_name': 'videojuego',
                'verbose_name_plural': 'videojuegos',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Videogame',
        ),
    ]
