# Generated by Django 4.0.4 on 2022-06-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0008_videogames_delete_videogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogames',
            name='calification',
            field=models.IntegerField(verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='content',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
